# Generated by Django 4.2.3 on 2023-08-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0003_alter_students_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='guardian_phone',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
