# Generated by Django 4.2.3 on 2023-08-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0008_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='Contact_no',
            new_name='contact_no',
        ),
    ]
