# Generated by Django 4.2.3 on 2023-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0010_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='s1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=6)),
                ('physics', models.CharField(max_length=3)),
                ('chemistry', models.CharField(max_length=3)),
                ('mathematics', models.CharField(max_length=3)),
                ('graphics', models.CharField(max_length=3)),
                ('electronics', models.CharField(max_length=3)),
            ],
        ),
    ]
