# Generated by Django 4.2.3 on 2023-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0011_s1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='id_no',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='s1',
            name='reg_no',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='students',
            name='reg_no',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id_no',
            field=models.CharField(max_length=4),
        ),
    ]
