# Generated by Django 4.2.3 on 2023-08-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0012_alter_principal_id_no_alter_s1_reg_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=10)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('clarification', models.TextField()),
            ],
        ),
    ]
