# Generated by Django 4.2.3 on 2023-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0013_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
