# Generated by Django 4.2.3 on 2023-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0015_rename_clarification_leave_desp'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=10)),
                ('upload_date', models.DateField()),
                ('filetype', models.CharField(max_length=30)),
                ('file', models.FileField(null=True, upload_to='')),
                ('status', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=30)),
            ],
        ),
    ]
