# Generated by Django 4.2.3 on 2023-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0020_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
