# Generated by Django 4.2.3 on 2023-09-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0022_delete_uploadedfile_alter_notes_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaydate', models.CharField(max_length=20)),
                ('todaytime', models.CharField(max_length=20)),
                ('lastdate', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=10)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
