# Generated by Django 4.2.3 on 2023-09-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0024_leave_reg_no_notes_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='s1',
            name='c_res',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='s1',
            name='e_res',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='s1',
            name='g_res',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='s1',
            name='m_res',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='s1',
            name='p_res',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
