# Generated by Django 4.2.3 on 2023-09-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0025_s1_c_res_s1_e_res_s1_g_res_s1_m_res_s1_p_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='s1',
            name='sem',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
